version: '3'
services:
    api:
        build: ./api
        ports:
            - "3000:3000"
        depends_on:
            - go_server
        links:
          - go_server
    go_server:
        build: ./server_golang
        ports:
          - "50051:50051"
        networks:
          static-network:
            ipv4_address: 172.20.128.2

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
#        - ip_range: 172.28.5.0/24
