# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import requests_mercadolibre_pb2 as requests__mercadolibre__pb2


class RequestStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RequestGo = channel.unary_unary(
        '/api.Request/RequestGo',
        request_serializer=requests__mercadolibre__pb2.ListURLs.SerializeToString,
        response_deserializer=requests__mercadolibre__pb2.Resp.FromString,
        )


class RequestServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RequestGo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RequestServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RequestGo': grpc.unary_unary_rpc_method_handler(
          servicer.RequestGo,
          request_deserializer=requests__mercadolibre__pb2.ListURLs.FromString,
          response_serializer=requests__mercadolibre__pb2.Resp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.Request', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
