# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import requests_mercadolibre_pb2 as requests__mercadolibre__pb2


class PingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/api.Ping/SayHello',
        request_serializer=requests__mercadolibre__pb2.PingMessage.SerializeToString,
        response_deserializer=requests__mercadolibre__pb2.PingMessage.FromString,
        )


class PingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=requests__mercadolibre__pb2.PingMessage.FromString,
          response_serializer=requests__mercadolibre__pb2.PingMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.Ping', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
